### ISSUE TITLE
notifier error when changing to Telegram GroupChat

### ISSUE THREAD

**Issue by roisec** [daniel-hauser/moneyman#283]
Hi @daniel-hauser  
I got an error when changing to group telegram chat.
I set on debug flag,
adding the relevant error
``` moneyman:scrape [max] END_SCRAPING +84ms
  moneyman:scrape ended +0ms
  moneyman:data scraping took 6.6s +7s
uncaughtException, sending error
  moneyman:notifier ❌ 
  moneyman:notifier Caught exception: Error: 429: Too Many Requests: retry after 31
  moneyman:notifier Exception origin: unhandledRejection +16s
uncaughtException, sending error
  moneyman:notifier ❌ 
  moneyman:notifier Caught exception: Error: 429: Too Many Requests: retry after 31
  moneyman:notifier Exception origin: unhandledRejection +19ms
  moneyman:main Error: 429: Too Many Requests: retry after 31
  moneyman:main     at Telegram.callApi (/Users//repos/moneyman/node_modules/telegraf/lib/core/network/client.js:315:19)
  moneyman:main     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  moneyman:main     at async editMessage (file:///Users//repos/moneyman/dst/notifier.js:19:13)
  moneyman:main     at async file:///Users//repos/moneyman/dst/index.js:30:21
  moneyman:main     at async file:///Users//repos/moneyman/dst/data/index.js:19:13
  moneyman:main     at async scrapeAccount (file:///Users//repos/moneyman/dst/data/index.js:41:5)
  moneyman:main     at async scrapeAccounts (file:///Users//repos/moneyman/dst/data/index.js:17:24)
  moneyman:main     at async Promise.all (index 0)
  moneyman:main     at async run (file:///Users//repos/moneyman/dst/index.js:27:31)
  moneyman:main     at async file:///Users//repos/moneyman/dst/index.js:14:1 +29s
  moneyman:notifier ❌ 429: Too Many Requests: retry after 31
  moneyman:notifier Error: 429: Too Many Requests: retry after 31
  moneyman:notifier     at Telegram.callApi (/Users//repos/moneyman/node_modules/telegraf/lib/core/network/client.js:315:19)
```

I guess the issue that edit message works frequest and cause telegram to rate limit the requests.

**Comment by roisec** [comment]
@daniel-hauser

**Comment by daniel-hauser** [comment]
Are you still getting this error? i didn't get it for a long time

**Comment by roisec** [comment]
I migrated from group chat. 
So I don’t have a problem with it.
