### ISSUE TITLE
GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY env variable string value not passing correctly to moneymen in Github Action secrets

### ISSUE THREAD

**Issue by nisan-tagar** [daniel-hauser/moneyman#384]
I am able to populate GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY in my local .env file with the string value (long string with escaped /n characters) and it works great locally.

When populating the same value in the Github Action secrets the value is not read correctly and I am getting this error trace from the google authentication library:

"
 error:1E08010C:DECODER routines::unsupported
Error: error:1E08010C:DECODER routines::unsupported
    at Sign.sign (node:internal/crypto/sig:128:29)
    at Object.sign (/app/node_modules/jwa/index.js:152:45)
    at Object.jwsSign [as sign] (/app/node_modules/jws/lib/sign-stream.js:32:24)
    at GoogleToken.requestToken (/app/node_modules/gtoken/build/src/index.js:224:31)
    at GoogleToken.getTokenAsyncInner (/app/node_modules/gtoken/build/src/index.js:158:21)
    at GoogleToken.getTokenAsync (/app/node_modules/gtoken/build/src/index.js:137:55)
    at GoogleToken.getToken (/app/node_modules/gtoken/build/src/index.js:96:21)
    at JWT.refreshTokenNoCache (/app/node_modules/google-auth-library/build/src/auth/jwtclient.js:173:36)
    at JWT.refreshToken (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:187:24)
    at JWT.getRequestMetadataAsync (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:333:28)
    at JWT.getRequestMetadataAsync (/app/node_modules/google-auth-library/build/src/auth/jwtclient.js:95:26)
    at JWT.getRequestHeaders (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:296:37)
    at GoogleAuth.getRequestHeaders (/app/node_modules/google-auth-library/build/src/auth/googleauth.js:731:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async j (file:///app/node_modules/google-spreadsheet/dist/index.mjs:1:21395)
    at async E._setAxiosRequestAuth (file:///app/node_modules/google-spreadsheet/dist/index.mjs:1:22385)
    at Axios.request (file:///app/node_modules/axios/lib/core/Axios.js:45:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async E.loadInfo (file:///app/node_modules/google-spreadsheet/dist/index.mjs:1:24482)
"

I suspect the root cause is due to the escape characters that are not read the same as in the local debug with the dotenv library but I was not able to fix it in the Action side with Github exec. 

Thanks in advance for any assistance with this issue!

**Comment by nisan-tagar** [comment]
Hey @daniel-hauser, have you encountered this issue before?

**Comment by daniel-hauser** [comment]
@nisan-tagar Yes, see: https://github.com/daniel-hauser/moneyman?tab=readme-ov-file#note

> docker doesn't support multiline environment variables (i.e. GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY), in that case you can run docker-compose up instead

Theoretically, we can change the code - but the easy solution is to use `docker-compose` or to manually remove the newlines (see link in #29)

**Comment by nisan-tagar** [comment]
Thanks @daniel-hauser for pointing that out to me. Unfortunately it did not solve the issue for me, but I was able to eventually solve the problem of using the private key in GitHub Actions by copying it to a file (by the Workflow) on the runner and mounting it to the docker container. Have a look here #385.
